"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['WRF_Analysis/main.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
 'iconfile': 'logo/WRF_logo.icns',
 'matplotlib_backends': 'tkagg,ps',
 'optimize': True,
 'packages': 'WRF_Analysis,numpy,scipy,PIL',
 'resources': 'WRF_Analysis/util/_StopPow.so'}

setup(
	name = "WRF_Analysis",
    version = "0.1",
    description = "WRF analysis utilities",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
